# Generated by Django 3.0.8 on 2020-07-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('idname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Namprod')),
            ],
        ),
    ]
