# Generated by Django 3.0.8 on 2020-07-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('idname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Namprod')),
                ('idpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Prodtype')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=100)),
                ('GB', models.IntegerField(max_length=11)),
                ('color', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('idpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Namprod')),
                ('idtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Productype')),
            ],
        ),
        migrations.CreateModel(
            name='pro_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Products')),
            ],
        ),
    ]
