# Generated by Django 3.0.8 on 2020-08-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_giohang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giohang',
            name='idpro',
        ),
        migrations.AddField(
            model_name='giohang',
            name='idpro',
            field=models.ManyToManyField(blank=True, to='home.Products'),
        ),
    ]
