# Generated by Django 3.0.8 on 2020-08-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200821_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giohang',
            name='idpro',
        ),
        migrations.AddField(
            model_name='giohang',
            name='Pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giohang', to='home.Products'),
        ),
        migrations.AddField(
            model_name='giohang',
            name='gia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='giohang',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='giohang',
            name='soluong',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
