# Generated by Django 3.0.8 on 2020-08-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200823_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giohang',
            name='Pro',
        ),
    ]
